---
title: "Research"
---

## Publications
1. Lee, C.-C., Wang, C.-W., & Xu, Z.-T. (2023). Signaling effect of cash holdings adjustment before bond issuance. *International Review of Financial Analysis*, 85, 102470. (SSCI, NSTC: A-) 
 
1. Wu, M.-T., & Xu, Z.-T. (2023). Has COVID-19 Strengthened the Stock Market Herding Effect? *Securities Market Development Quarterly*, 35(3), 1-32. (TSSCI Tier 1) 
 
1. Lee, C.-C., Wang, C.-W., & Xu, Z.-T. (2023). Managerial ability and R&D investment: Do CEOs’ and firms’ characteristics matter? *Applied Economics*, 56(26), 3150–3165. (SSCI, NSTC: B) 
 
1. Lee, C.-C., Wang, C.-W., Thinh, B. T., & Xu, Z.-T. (2022). Climate risk and bank liquidity creation: International evidence. *International Review of Financial Analysis*, 82, 102198. (SSCI, NSTC: A-)

## Conference
1. Chou, P.-H., Xu, Z.-T., & Huang, G.-Y. (2026, May). ESG rating, investor heterogeneity, and firm risk: An asset-pricing perspective. 2026 TFA Conference, New Taipei, Taiwan. 經過評選獲得「宏利投信 X 安本投資 ESG－永續投資與發展論文獎」教師與研究人員組優等